name: Test disassemble and reassemble

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-rom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install RGBDS
        run: |
          RGBDS_VERSION=$(curl -s https://api.github.com/repos/gbdev/rgbds/releases/latest | grep -oP '"tag_name": "\K(.*?)(?=")')
          RGBDS_FILE="rgbds-${RGBDS_VERSION#v}-linux-x86_64.tar.xz"
          RGBDS_URL="https://github.com/gbdev/rgbds/releases/download/${RGBDS_VERSION}/${RGBDS_FILE}"
          
          # Create a temporary directory for extraction
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"

          # Download and extract RGBDS
          wget -q "$RGBDS_URL"
          tar -xJf "$RGBDS_FILE"

          # Install using install.sh
          sudo ./install.sh

          # Cleanup
          cd ..
          rm -rf "$TEMP_DIR"

      - name: Show RGBDS version
        run: rgbasm --version

      - name: Run Makefile
        run: make -C test
