name: Test disassemble and reassemble

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-rom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rgbds python3 python3-pip

      - name: Show RGBDS version
        run: rgbasm --version

      - name: Run Makefile
        run: make -C test
